"use client";
import { FormEvent, useEffect, useState } from "react";
import { DEFAULT_CRM_CONFIG, type CrmConfig, type CrmModuleKey } from "@/lib/crm/config";

const moduleLabels: Record<CrmModuleKey,string> = {
  photos:"Photos & files", workforce:"Workforce / assigned people", commission:"Commission",
  payments:"Customer payments", costs:"Costs & profit", finishes:"Finishes / specifications", siteVisits:"Site visits & scheduling",
};
const rolePresets=["Installer","Engineer","Technician","Contractor","Subcontractor","Surveyor","Project manager","Electrician","Plumber","Carpenter","Builder","Cleaner","Driver","Consultant","Salesperson","Fabricator","Other"];

export default function SettingsPage(){
 const [s,setS]=useState<CrmConfig>(DEFAULT_CRM_CONFIG),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/admin/settings",{cache:"no-store"}).then(async r=>{if(r.ok){const b=await r.json();setS(b.settings);}setLoading(false);});},[]);
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");const r=await fetch("/api/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(s)});setSaving(false);setMessage(r.ok?"Settings saved":"Could not save settings");}
 async function logo(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);setMessage("Uploading logo...");const r=await fetch("/api/admin/settings",{method:"POST",body:fd});const b=await r.json().catch(()=>({}));if(r.ok){setS(b.settings);setMessage("Logo updated");}else setMessage(b.error||"Could not upload logo");}
 function module(key:CrmModuleKey,value:boolean){setS(v=>({...v,modules:{...v.modules,[key]:value}}));}
 if(loading)return <main className="min-h-screen bg-[#f4f4f1] p-8">Loading settings...</main>;
 return <main className="min-h-screen bg-[#f4f4f1] text-[#141414]"><div className="mx-auto max-w-4xl px-4 py-7"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-[#e66a24]">CRM configuration</p><h1 className="text-3xl font-black">Business & system settings</h1><p className="mt-1 text-sm text-black/50">These settings are shared across the business, not just this device.</p></div><a href="/admin" className="rounded-xl border border-black/15 bg-white px-4 py-2 text-sm font-bold">Back</a></div>
 <section className="mb-5 rounded-2xl border border-black/10 bg-white p-5"><h2 className="text-lg font-black">Branding</h2><div className="mt-4 flex items-center gap-4"><img src={s.logoUrl} alt="" className="h-16 max-w-48 object-contain"/><form onSubmit={logo} className="flex flex-wrap gap-2"><input name="logo" type="file" accept="image/*" required className="text-sm"/><button className="rounded-xl bg-black px-4 py-2 text-sm font-black text-white">Upload / change logo</button></form></div></section>
 <form onSubmit={save} className="space-y-5">
 <section className="rounded-2xl border border-black/10 bg-white p-5"><h2 className="text-lg font-black">Names & appearance</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Business name<input value={s.businessName} onChange={e=>setS({...s,businessName:e.target.value})} className="mt-1 block h-11 w-full rounded-xl border border-black/15 px-3"/></label><label className="text-sm font-bold">Name shown at the top of your system<span className="mt-0.5 block text-xs font-normal text-black/45">For example: CRM & Job Management, Service Management or My Business Hub.</span><input value={s.systemName} onChange={e=>setS({...s,systemName:e.target.value})} className="mt-1 block h-11 w-full rounded-xl border border-black/15 px-3"/></label><label className="text-sm font-bold">Accent colour<input type="color" value={s.accentColour} onChange={e=>setS({...s,accentColour:e.target.value})} className="mt-1 block h-11 w-full rounded-xl border border-black/15 bg-white p-1"/></label></div></section>
 <section className="rounded-2xl border border-black/10 bg-white p-5"><h2 className="text-lg font-black">What this business uses</h2><p className="mt-1 text-sm text-black/50">Turn off modules the business does not need. Hidden modules can be switched back on later.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{(Object.keys(moduleLabels) as CrmModuleKey[]).map(k=><label key={k} className="flex items-center justify-between rounded-xl border border-black/10 p-3 text-sm font-bold"><span>{moduleLabels[k]}</span><input type="checkbox" checked={s.modules[k]} onChange={e=>module(k,e.target.checked)}/></label>)}</div></section>
 <section className="rounded-2xl border border-black/10 bg-white p-5"><h2 className="text-lg font-black">People assigned to jobs</h2><p className="mt-1 text-sm text-black/50">Choose the wording your team already uses, such as Engineers, Installers, Contractors or Subcontractors.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">What should this section be called?<input value={s.workforceTitle} onChange={e=>setS({...s,workforceTitle:e.target.value})} className="mt-1 block h-11 w-full rounded-xl border border-black/15 px-3"/></label><label className="text-sm font-bold">What should one person be called?<span className="mt-0.5 block text-xs font-normal text-black/45">For example: engineer, installer or team member.</span><input value={s.workforceSingular} onChange={e=>setS({...s,workforceSingular:e.target.value})} className="mt-1 block h-11 w-full rounded-xl border border-black/15 px-3"/></label></div><div className="mt-4"><p className="mb-2 text-sm font-bold">Roles used by this business</p><select defaultValue="" className="h-11 w-full rounded-xl border border-black/15 bg-white px-3 text-sm" onChange={e=>{const role=e.target.value;if(role&&!s.workforceRoles.includes(role))setS({...s,workforceRoles:[...s.workforceRoles,role]});e.currentTarget.value="";}}><option value="">Add a role...</option>{rolePresets.filter(role=>!s.workforceRoles.includes(role)).map(role=><option key={role}>{role}</option>)}</select><div className="mt-2 flex flex-wrap gap-2">{s.workforceRoles.map(role=><span key={role} className="rounded-full border border-black/15 bg-white px-3 py-1.5 text-xs font-bold">{role}<button type="button" onClick={()=>setS({...s,workforceRoles:s.workforceRoles.filter(x=>x!==role)})} className="ml-2 text-red-600" aria-label={`Remove ${role}`}>×</button></span>)}</div><input placeholder="Or add your own role and press Enter" className="mt-3 h-10 w-full rounded-xl border border-black/15 px-3 text-sm" onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();const value=e.currentTarget.value.trim();if(value&&!s.workforceRoles.includes(value))setS({...s,workforceRoles:[...s.workforceRoles,value]});e.currentTarget.value="";}}}/></div></section>
 <div className="flex items-center justify-end gap-3 pb-8">{message&&<span className="text-sm font-bold">{message}</span>}<button disabled={saving} className="rounded-xl bg-[#e66a24] px-5 py-3 text-sm font-black text-white">{saving?"Saving...":"Save settings"}</button></div>
 </form></div></main>;
}