"use client";
import {FormEvent,useEffect,useState} from "react";

export default function AiAssistantPage(){
 const[question,setQuestion]=useState("");const[answer,setAnswer]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[allowed,setAllowed]=useState<boolean|null>(null);
 useEffect(()=>{fetch("/api/demo/settings",{cache:"no-store"}).then(async r=>{if(!r.ok){setAllowed(false);return}const b=await r.json();const s=b.settings;setAllowed(Boolean(s?.billing?.mode==="free"||s?.plan?.aiIncluded));}).catch(()=>setAllowed(false));},[]);
 async function ask(e:FormEvent){e.preventDefault();if(!question.trim()||busy)return;setBusy(true);setError("");setAnswer("");const r=await fetch("/api/demo/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question})});const b=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setError(b.error||"Could not ask AI Assistant");return}setAnswer(String(b.answer||""));}
 function listen(){const w=window as any;const SpeechRecognition=w.SpeechRecognition||w.webkitSpeechRecognition;if(!SpeechRecognition){setError("Voice input is not supported by this browser.");return}const recognition=new SpeechRecognition();recognition.lang="en-GB";recognition.interimResults=false;recognition.onresult=(event:any)=>setQuestion(event.results?.[0]?.[0]?.transcript||"");recognition.onerror=()=>setError("Voice input could not start.");recognition.start();}
 function speak(){if(!answer||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(answer);u.lang="en-GB";window.speechSynthesis.speak(u);}
 if(allowed===false)return <main className="min-h-screen bg-[#f5f5f2] p-6 lg:p-10"><div className="mx-auto max-w-3xl rounded-2xl border border-black/10 bg-white p-7"><h1 className="text-2xl font-black">AI Assistant</h1><p className="mt-3 text-black/60">AI Assistant is not included in this Business Software subscription.</p></div></main>;
 return <main className="min-h-screen bg-[#f5f5f2] p-5 lg:p-8"><div className="mx-auto max-w-4xl"><p className="text-xs font-black uppercase tracking-[.14em] text-[#e66a24]">Diamant Solutions</p><h1 className="mt-1 text-3xl font-black">AI Assistant</h1><p className="mt-2 text-sm text-black/55">Ask about your jobs, next actions and recent business activity. The assistant is read-only and cannot change records.</p><form onSubmit={ask} className="mt-6 rounded-2xl border border-black/10 bg-white p-5 shadow-sm"><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="e.g. What needs my attention today?" className="min-h-28 w-full resize-y rounded-xl border border-black/15 p-3 outline-none focus:border-[#e66a24]"/><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy||!question.trim()} className="rounded-xl bg-[#141414] px-5 py-2.5 text-sm font-black text-white disabled:opacity-40">{busy?"Thinking...":"Ask AI"}</button><button type="button" onClick={listen} className="rounded-xl border border-black/15 bg-white px-4 py-2.5 text-sm font-black">🎙 Voice input</button></div>{error&&<p className="mt-3 text-sm font-bold text-red-700">{error}</p>}</form>{answer&&<section className="mt-5 rounded-2xl border border-black/10 bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-3"><h2 className="font-black">Answer</h2><button onClick={speak} className="rounded-lg border border-black/15 px-3 py-1.5 text-xs font-black">🔊 Read aloud</button></div><div className="mt-4 whitespace-pre-wrap text-sm leading-7 text-black/75">{answer}</div></section>}</div></main>;
}
