import crypto from "node:crypto";
import { supabaseRequest } from "@/lib/crm/supabase-server";

const AUTHORIZE_URL="https://accounts.google.com/o/oauth2/v2/auth";
const TOKEN_URL="https://oauth2.googleapis.com/token";
const USERINFO_URL="https://openidconnect.googleapis.com/v1/userinfo";
const GMAIL_SEND_URL="https://gmail.googleapis.com/gmail/v1/users/me/messages/send";
const SCOPES=["openid","email","https://www.googleapis.com/auth/gmail.send"].join(" ");
const STORAGE_PATH="_crm/gmail.json";

type GoogleToken={access_token:string;refresh_token?:string;expires_in:number;scope?:string};
type Stored={email:string;accessToken:string;refreshToken:string;expiresAt:string;connectedAt:string;connectedBy:string};

function cfg(){const clientId=process.env.GOOGLE_CLIENT_ID,clientSecret=process.env.GOOGLE_CLIENT_SECRET,redirectUri=process.env.GOOGLE_GMAIL_REDIRECT_URI;if(!clientId||!clientSecret||!redirectUri)throw new Error("Google / Gmail integration is not configured");return{clientId,clientSecret,redirectUri};}
function key(){return crypto.createHash("sha256").update(cfg().clientSecret).digest();}
function enc(v:string){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv("aes-256-gcm",key(),iv),out=Buffer.concat([cipher.update(v,"utf8"),cipher.final()]);return[iv.toString("base64url"),cipher.getAuthTag().toString("base64url"),out.toString("base64url")].join(".");}
function dec(v:string){const[a,b,c]=v.split(".");if(!a||!b||!c)throw new Error("Invalid encrypted Google token");const d=crypto.createDecipheriv("aes-256-gcm",key(),Buffer.from(a,"base64url"));d.setAuthTag(Buffer.from(b,"base64url"));return Buffer.concat([d.update(Buffer.from(c,"base64url")),d.final()]).toString("utf8");}
function p(){return STORAGE_PATH.split("/").map(encodeURIComponent).join("/");}

export function googleAuthorizeUrl(state:string){const{clientId,redirectUri}=cfg();return `${AUTHORIZE_URL}?${new URLSearchParams({client_id:clientId,redirect_uri:redirectUri,response_type:"code",scope:SCOPES,access_type:"offline",prompt:"consent",state}).toString()}`;}
async function tokenRequest(params:URLSearchParams){const{clientId,clientSecret}=cfg();params.set("client_id",clientId);params.set("client_secret",clientSecret);const r=await fetch(TOKEN_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:params,cache:"no-store"});if(!r.ok)throw new Error("Google authorisation failed");return r.json() as Promise<GoogleToken>;}
export async function exchangeGoogleCode(code:string){const{redirectUri}=cfg();return tokenRequest(new URLSearchParams({grant_type:"authorization_code",code,redirect_uri:redirectUri}));}
export async function googleEmail(accessToken:string){const r=await fetch(USERINFO_URL,{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"});if(!r.ok)throw new Error("Could not read connected Google account");const b=await r.json() as {email?:string};if(!b.email)throw new Error("Google account has no email address");return b.email;}
export async function saveGoogleConnection(sessionToken:string,userId:string,token:GoogleToken,email:string){if(!token.refresh_token)throw new Error("Google did not return offline access. Reconnect and approve access.");const stored:Stored={email,accessToken:enc(token.access_token),refreshToken:enc(token.refresh_token),expiresAt:new Date(Date.now()+token.expires_in*1000).toISOString(),connectedAt:new Date().toISOString(),connectedBy:userId};const r=await supabaseRequest(`/storage/v1/object/mj-job-files/${p()}`,{method:"POST",headers:{"Content-Type":"application/json","x-upsert":"true"},body:JSON.stringify(stored)},sessionToken);if(!r.ok)throw new Error("Could not save Gmail connection");}
export async function getStoredGoogleConnection(sessionToken:string){const r=await supabaseRequest(`/storage/v1/object/mj-job-files/${p()}`,{method:"GET"},sessionToken);if(r.status===404)return null;if(!r.ok)throw new Error("Could not load Gmail connection");return r.json() as Promise<Stored>;}
export async function getValidGoogleConnection(sessionToken:string){const s=await getStoredGoogleConnection(sessionToken);if(!s)return null;if(Date.parse(s.expiresAt)>Date.now()+120000)return{email:s.email,accessToken:dec(s.accessToken)};const t=await tokenRequest(new URLSearchParams({grant_type:"refresh_token",refresh_token:dec(s.refreshToken)}));const updated:Stored={...s,accessToken:enc(t.access_token),expiresAt:new Date(Date.now()+t.expires_in*1000).toISOString()};const r=await supabaseRequest(`/storage/v1/object/mj-job-files/${p()}`,{method:"POST",headers:{"Content-Type":"application/json","x-upsert":"true"},body:JSON.stringify(updated)},sessionToken);if(!r.ok)throw new Error("Could not refresh Gmail connection");return{email:s.email,accessToken:t.access_token};}
export async function disconnectGoogle(sessionToken:string){const r=await supabaseRequest(`/storage/v1/object/mj-job-files/${p()}`,{method:"DELETE"},sessionToken);if(!r.ok&&r.status!==404)throw new Error("Could not disconnect Gmail");}
function b64url(v:string|Buffer){return Buffer.from(v).toString("base64").replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");}
export async function sendGmail(accessToken:string,args:{fromName:string;fromEmail:string;to:string;replyTo?:string;subject:string;html:string;attachment?:{filename:string;content:Buffer;mimeType:string}}){const boundary=`crm_${crypto.randomBytes(12).toString("hex")}`;const headers=[`From: ${args.fromName} <${args.fromEmail}>`,`To: ${args.to}`,`Subject: =?UTF-8?B?${Buffer.from(args.subject).toString("base64")}?=`,args.replyTo?`Reply-To: ${args.replyTo}`:"","MIME-Version: 1.0",`Content-Type: multipart/mixed; boundary="${boundary}"`].filter(Boolean).join("\r\n");let raw=`${headers}\r\n\r\n--${boundary}\r\nContent-Type: text/html; charset=UTF-8\r\nContent-Transfer-Encoding: base64\r\n\r\n${Buffer.from(args.html).toString("base64")}\r\n`;if(args.attachment)raw+=`--${boundary}\r\nContent-Type: ${args.attachment.mimeType}; name="${args.attachment.filename}"\r\nContent-Disposition: attachment; filename="${args.attachment.filename}"\r\nContent-Transfer-Encoding: base64\r\n\r\n${args.attachment.content.toString("base64")}\r\n`;raw+=`--${boundary}--`;const r=await fetch(GMAIL_SEND_URL,{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({raw:b64url(raw)}),cache:"no-store"});if(!r.ok){const e=await r.json().catch(()=>null);throw new Error(e?.error?.message||"Gmail could not send the message");}return r.json();}
