import { NextRequest, NextResponse } from "next/server";
import { requirePermission } from "@/lib/crm/supabase-server";
import { ALL_PERMISSIONS, ROLE_PERMISSIONS, type PermissionKey, type UserRole } from "@/lib/crm/permissions";
import { loadCrmUsers, saveCrmUsers } from "@/lib/crm/user-access";

function cleanPermissions(value:unknown,role:UserRole){const wanted=Array.isArray(value)?value.map(String):ROLE_PERMISSIONS[role]||[];return wanted.filter((x):x is PermissionKey=>ALL_PERMISSIONS.includes(x as PermissionKey));}
export async function GET(){const session=await requirePermission("manage_users");if(!session)return NextResponse.json({error:"Unauthorised"},{status:401});const users=await loadCrmUsers(session.token);return NextResponse.json({users,plan:null,seatCount:users.filter(u=>u.status!=="disabled").length,seatLimit:2,canAdd:users.filter(u=>u.status!=="disabled").length<2,billingConnected:false,pricingConnected:false,message:null,currentUserId:session.accessUser.id});}
export async function POST(request:NextRequest){const session=await requirePermission("manage_users");if(!session)return NextResponse.json({error:"Unauthorised"},{status:401});const users=await loadCrmUsers(session.token);if(users.filter(u=>u.status!=="disabled").length>=2)return NextResponse.json({error:"seat_limit",message:"Your current plan allows 2 users. Upgrade to add another user."},{status:409});const body=await request.json().catch(()=>({}));const role=String(body.role||"custom") as UserRole;if(role==="owner")return NextResponse.json({error:"Owner access cannot be assigned here."},{status:400});return NextResponse.json({error:"invites_not_ready",message:"User invitations are not available yet."},{status:503});}
export async function PATCH(request:NextRequest){const session=await requirePermission("manage_users");if(!session)return NextResponse.json({error:"Unauthorised"},{status:401});const body=await request.json().catch(()=>({}));const users=await loadCrmUsers(session.token);const i=users.findIndex(u=>u.id===String(body.id));if(i<0)return NextResponse.json({error:"User not found"},{status:404});const current=users[i];if(current.protectedOwner||current.role==="owner")return NextResponse.json({error:"The owner account is protected."},{status:403});const role=String(body.role||current.role) as UserRole;if(role==="owner")return NextResponse.json({error:"Owner access cannot be assigned here."},{status:400});users[i]={...current,role,permissions:cleanPermissions(body.permissions,role),status:body.status==="disabled"?"disabled":"active"};await saveCrmUsers(session.token,users);return NextResponse.json({user:users[i]});}
