"use client";
import { useEffect,useState } from "react";
import { PERMISSION_LABELS,ROLE_LABELS,ROLE_PERMISSIONS,type PermissionKey,type UserRole } from "@/lib/crm/permissions";
export default function UsersPage(){const [data,setData]=useState<any>(null),[role,setRole]=useState<UserRole>("field"),[permissions,setPermissions]=useState<PermissionKey[]>(ROLE_PERMISSIONS.field),[msg,setMsg]=useState("");
useEffect(()=>{fetch("/api/admin/users",{cache:"no-store"}).then(r=>r.json()).then(setData)},[]);
function chooseRole(v:UserRole){setRole(v);setPermissions(ROLE_PERMISSIONS[v]);}
async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const r=await fetch("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:fd.get("name"),email:fd.get("email"),role,permissions})});const b=await r.json();setMsg(b.message||"Unable to add user");}
return (<main className="min-h-screen bg-[#f4f4f1]"><div className="mx-auto max-w-4xl px-4 py-7">
<div className="mb-6 flex justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-[#e66a24]">Access control</p><h1 className="text-3xl font-black">Users & permissions</h1><p className="mt-1 text-sm text-black/50">Control what each person can see and change.</p></div><a href="/admin" className="h-fit rounded-xl border border-black/15 bg-white px-4 py-2 text-sm font-bold">Back</a></div>
<section className="rounded-2xl bg-white p-5"><div className="flex justify-between gap-3"><h2 className="font-black">Current users</h2><span className="text-sm font-bold">{data?.seatLimit?`${data.seatCount} out of ${data.seatLimit} ${data.seatLimit===1?"user":"users"}`:`${data?.seatCount??0} ${(data?.seatCount??0)===1?"user":"users"}`}</span></div><div className="mt-3 space-y-2">{data?.users?.map((u:any)=><div key={u.id} className="flex justify-between rounded-xl border border-black/10 p-3"><b>{u.name}</b><span className="text-sm text-black/50">{ROLE_LABELS[u.role as UserRole]||"User"}</span></div>)}</div></section>
<section className="mt-5 rounded-2xl bg-white p-5">{data?.seatLimit&&data.seatCount>=data.seatLimit?<><h2 className="font-black">Need another user?</h2><div className="mt-3 rounded-xl bg-amber-50 p-4 text-sm"><b>Your current plan is full.</b><p className="mt-1 text-black/60">Upgrade your account to add more users.</p>{data?.pricingConnected&&<button type="button" className="mt-3 rounded-lg bg-black px-4 py-2 text-xs font-black text-white">Upgrade account</button>}</div></>:<><h2 className="font-black">Add a user</h2><form onSubmit={add} className="mt-4 space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Name<input name="name" required className="mt-1 h-11 w-full rounded-xl border border-black/15 px-3"/></label><label className="text-sm font-bold">Email<input name="email" type="email" required className="mt-1 h-11 w-full rounded-xl border border-black/15 px-3"/></label></div><label className="block text-sm font-bold">Role<select value={role} onChange={e=>chooseRole(e.target.value as UserRole)} className="mt-1 h-11 w-full rounded-xl border border-black/15 bg-white px-3">{(["admin","manager","office","sales","field","custom"] as UserRole[]).map(x=><option key={x} value={x}>{ROLE_LABELS[x]}</option>)}</select></label><div><p className="mb-2 text-sm font-bold">Permissions</p><div className="grid gap-2 sm:grid-cols-2">{(Object.keys(PERMISSION_LABELS) as PermissionKey[]).filter(k=>k!=="manage_subscription").map(k=><label key={k} className="flex items-center gap-2 rounded-xl border border-black/10 p-3 text-sm"><input type="checkbox" checked={permissions.includes(k)} onChange={e=>{setRole("custom");setPermissions(v=>e.target.checked?[...v,k]:v.filter(x=>x!==k))}}/>{PERMISSION_LABELS[k]}</label>)}</div></div><button className="rounded-xl bg-[#e66a24] px-5 py-3 text-sm font-black text-white">Add user</button>{msg&&<p className="text-sm font-bold">{msg}</p>}</form></>}</section>
</div></main>)}