"use client";
import {useEffect,useMemo,useState} from "react";
import {STATUS_META} from "@/lib/crm/constants";
import type {Manager} from "@/lib/crm/types";
import Link from "next/link";
type View="customers"|"jobs"|"quotes"|"invoices"|"payments"|"files"|"team";
const titles:any={customers:["Customers","Every customer and their jobs in one place."],jobs:["Jobs","All current work and enquiries."],quotes:["Quotes","Quotes across every job."],invoices:["Invoices","Jobs at invoice and payment stage."],payments:["Payments","Customer payments and outstanding balances."],files:["Files","Open job files and photos from one place."],team:["Team","People assigned across your work."]};
const money=(v:any)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(Number(v||0));
export default function BusinessDirectory({view}:{view:View}){const [jobs,setJobs]=useState<any[]>([]),[people,setPeople]=useState<any[]>([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[sort,setSort]=useState("default"),[jobType,setJobType]=useState("all"),[manager,setManager]=useState<Manager|"all">("all"),[showHistoricalInvoice,setShowHistoricalInvoice]=useState(false);useEffect(()=>{fetch("/api/admin/jobs",{cache:"no-store"}).then(async r=>{if(r.status===401){location.href="/admin/login";return;}const b=await r.json();if(!r.ok)setError(b.error||"Unable to load records");else{setJobs((b.jobs||[]).filter((x:any)=>!x.isPlaceholder));setPeople(b.people||[]);}setLoading(false);}).catch(()=>{setError("Unable to load records");setLoading(false);});},[]);
const rows=useMemo(()=>{const s=q.toLowerCase().trim();return jobs.filter(j=>!s||[j.reference,j.customerName,j.address,j.postcode,j.jobType,j.email,j.phone].join(" ").toLowerCase().includes(s));},[jobs,q]);
const customers=useMemo(()=>{const m=new Map<string,any>();rows.forEach(j=>{const k=j.customerId||j.customerName;const x=m.get(k)||{id:k,name:j.customerName,email:j.email,phone:j.phone,address:j.address,postcode:j.postcode,jobs:[]};x.jobs.push(j);m.set(k,x);});return [...m.values()].sort((a,b)=>a.name.localeCompare(b.name));},[rows]);
const payments=rows.flatMap(j=>(j.customerPayments||[]).map((p:any)=>({...p,job:j})));
const jobTypes=useMemo(()=>Array.from(new Set(jobs.flatMap(j=>j.jobTypes||[j.jobType]).filter(Boolean))).sort(),[jobs]);
const [title,desc]=titles[view];
const statuses=useMemo(()=>Array.from(new Set(jobs.map(j=>String(j.status||""))).values()).filter(Boolean).sort(),[jobs]);
const [statusFilter,setStatusFilter]=useState("all");
const visibleRows=useMemo(()=>{const filtered=rows.filter(j=>(statusFilter==="all"||j.status===statusFilter)&&(jobType==="all"||(j.jobTypes||[j.jobType]).includes(jobType))&&(manager==="all"||j.manager===manager));return [...filtered].sort((a,b)=>{if(sort==="customer")return String(a.customerName||"").localeCompare(String(b.customerName||""));if(sort==="value_desc")return Number(b.quotedAmount??b.preliminaryEstimate??0)-Number(a.quotedAmount??a.preliminaryEstimate??0);if(sort==="value_asc")return Number(a.quotedAmount??a.preliminaryEstimate??0)-Number(b.quotedAmount??b.preliminaryEstimate??0);if(sort==="oldest")return Number(a.sequenceNumber||0)-Number(b.sequenceNumber||0);return Number(b.sequenceNumber||0)-Number(a.sequenceNumber||0);});},[rows,statusFilter,jobType,manager,sort]);
const quoteRows=useMemo(()=>visibleRows.filter(j=>j.latestQuote?.id),[visibleRows]);
const invoiceRows=useMemo(()=>visibleRows.filter(j=>j.hasInvoice),[visibleRows]);
const sortedPayments=useMemo(()=>[...payments].sort((a,b)=>{const ad=new Date(a.paid_at||a.created_at||0).getTime(),bd=new Date(b.paid_at||b.created_at||0).getTime();if(sort==="oldest")return ad-bd;if(sort==="value_desc")return Number(b.amount||0)-Number(a.amount||0);if(sort==="value_asc")return Number(a.amount||0)-Number(b.amount||0);return bd-ad;}),[payments,sort]);
useEffect(()=>{if(view==="customers"||view==="team")setSort("customer");else setSort("default");},[view]);
return <main className="min-h-screen bg-[#f5f5f2] px-4 py-7 text-[#141414] sm:px-5 lg:px-8"><div className="mx-auto max-w-[1500px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#e66a24]">Business Management Software</p><h1 className="mt-1 text-3xl font-black">{title}</h1><p className="mt-1 text-sm text-black/50">{desc}</p></div>{view==="jobs"&&<Link href="/admin/jobs/new" className="rounded-xl bg-[#e66a24] px-4 py-2.5 text-sm font-black text-white">+ New job</Link>}{view==="invoices"&&<button onClick={()=>setShowHistoricalInvoice(true)} className="rounded-xl bg-[#e66a24] px-4 py-2.5 text-sm font-black text-white">+ Add historical invoice</button>}</div><div className="mt-5 rounded-2xl border border-black/10 bg-white p-3"><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-[minmax(240px,1fr)_190px_190px_190px_210px]"><input value={q} onChange={e=>setQ(e.target.value)} placeholder={"Search "+title.toLowerCase()+"..."} className="h-11 w-full rounded-xl border border-black/15 px-3 text-sm outline-none"/>{!["customers","team"].includes(view)&&<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="h-11 rounded-xl border border-black/15 bg-white px-3 text-sm font-bold"><option value="all">All statuses</option>{statuses.map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select>}{["jobs","quotes","invoices","files"].includes(view)&&<select value={jobType} onChange={e=>setJobType(e.target.value)} className="h-11 rounded-xl border border-black/15 bg-white px-3 text-sm font-bold"><option value="all">All job types</option>{jobTypes.map(t=><option key={String(t)} value={String(t)}>{String(t)}</option>)}</select>}{view==="jobs"&&<select value={manager} onChange={e=>setManager(e.target.value as Manager|"all")} className="h-11 rounded-xl border border-black/15 bg-white px-3 text-sm font-bold"><option value="all">All managers</option><option value="MD">Mark</option><option value="JB">Jonathan</option></select>}{!["customers","team","files"].includes(view)&&<select value={sort} onChange={e=>setSort(e.target.value)} className="h-11 rounded-xl border border-black/15 bg-white px-3 text-sm font-bold"><option value="default">{view==="payments"?"Newest payment first":"Newest job first"}</option><option value="oldest">{view==="payments"?"Oldest payment first":"Oldest job first"}</option>{view!=="payments"&&<option value="customer">Customer A-Z</option>}<option value="value_desc">Highest amount first</option><option value="value_asc">Lowest amount first</option></select>}</div></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}{loading&&<p className="mt-5 rounded-2xl bg-white p-8 text-center text-black/45">Loading...</p>}
{!loading&&view==="customers"&&<div className="mt-5 grid gap-3">{customers.map(c=><section key={c.id} className="rounded-2xl border border-black/10 bg-white p-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-black">{c.name}</h2><p className="text-xs text-black/50">{[c.address,c.postcode,c.email,c.phone].filter(Boolean).join(" · ")}</p></div><b>{c.jobs.length} job{c.jobs.length===1?"":"s"}</b></div><div className="mt-3 flex flex-wrap gap-2">{c.jobs.map((j:any)=><Link key={j.id} href={"/admin/jobs/"+j.reference} className="rounded-lg bg-[#f5f5f2] px-3 py-2 text-xs font-bold"><span className="text-[#e66a24]">{j.reference}</span> · {j.jobType}</Link>)}</div></section>)}</div>}
{!loading&&view==="jobs"&&<Table rows={visibleRows} cols={["Job","Customer","Work","Status","Value"]} render={j=>[<Link className="font-black text-[#e66a24]" href={"/admin/jobs/"+j.reference}>{j.reference}</Link>,j.customerName,j.jobType,<Status value={j.status}/>,money(j.quotedAmount??j.preliminaryEstimate)]}/>}
{!loading&&view==="quotes"&&<Table rows={quoteRows} cols={["Job","Customer","Estimate","Final quote","Sent"]} render={j=>[<Link className="font-black text-[#e66a24]" href={"/admin/jobs/"+j.reference}>{j.reference}</Link>,j.customerName,money(j.preliminaryEstimate),j.quotedAmount!=null?money(j.quotedAmount):"Not finalised",j.quoteDisplaySent?(j.quoteSentAt?new Date(j.quoteSentAt).toLocaleDateString("en-GB"):"Sent"):"Draft"]}/>}
{!loading&&view==="invoices"&&<Table rows={invoiceRows} cols={["Job","Customer","Payment status","Job value","Received","Outstanding"]} render={j=>[<Link className="font-black text-[#e66a24]" href={"/admin/jobs/"+j.reference}>{j.reference}</Link>,j.customerName,<span className={"inline-flex rounded-full px-2.5 py-1 text-xs font-black "+(paymentState(j)==="Paid"?"bg-green-100 text-green-700":paymentState(j)==="Part-paid"?"bg-amber-100 text-amber-800":"bg-red-100 text-red-700")}>{paymentState(j)}</span>,money(j.quotedAmount),money(j.amountPaid),money(j.balanceOutstanding)]}/>}
{!loading&&view==="payments"&&<><div className="mt-5 grid gap-3 sm:grid-cols-3"><Stat label="Received" value={money(rows.reduce((s,j)=>s+Number(j.amountPaid||0),0))}/><Stat label="Outstanding" value={money(rows.reduce((s,j)=>s+Number(j.balanceOutstanding||0),0))}/><Stat label="Payments recorded" value={String(payments.length)}/></div><Table rows={sortedPayments} cols={["Job","Customer","Payment","Date","Amount"]} render={p=>[<Link className="font-black text-[#e66a24]" href={"/admin/jobs/"+p.job.reference}>{p.job.reference}</Link>,p.job.customerName,p.payment_type||"Payment",new Date(p.paid_at||p.created_at).toLocaleDateString("en-GB"),money(p.amount)]}/></>}
{!loading&&view==="files"&&<div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{visibleRows.map(j=><Link key={j.id} href={"/admin/jobs/"+j.reference} className="rounded-2xl border border-black/10 bg-white p-4 hover:bg-[#fffaf6]"><b className="text-[#e66a24]">{j.reference}</b><h2 className="mt-1 font-black">{j.customerName}</h2><p className="mt-1 text-sm text-black/50">{j.jobType}</p><p className="mt-4 text-xs font-bold">Open photos & files →</p></Link>)}</div>}
{showHistoricalInvoice&&<HistoricalInvoiceModal jobs={jobs} onClose={()=>setShowHistoricalInvoice(false)} onSaved={()=>location.reload()}/>}\n{!loading&&view==="team"&&<div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{people.map((p:any)=><section key={p.id} className="rounded-2xl border border-black/10 bg-white p-4"><h2 className="font-black">{p.name}</h2><p className="text-sm text-black/50">{p.company||String(p.relationship_type||"Team member").replaceAll("_"," ")}</p></section>)}</div>}</div></main>}
function paymentState(j:any){const due=Number(j.balanceOutstanding||0),paid=Number(j.amountPaid||0);return due<=0&&paid>0?"Paid":paid>0?"Part-paid":"Unpaid"}
function statusLabel(value:any){return STATUS_META[value as keyof typeof STATUS_META]?.label??String(value||"").replaceAll("_"," ")}
function rowTone(value:any){const s=String(value||"").toLowerCase();if(s==="declined"||s==="cancelled")return "bg-red-50/80";if(s==="completed")return "bg-green-50/80";if(s==="in_progress")return "bg-blue-50/80";if(s==="awaiting_final_payment")return "bg-amber-50/80";if(s.includes("await")||s.includes("estimate")||s.includes("quote"))return "bg-orange-50/55";return "bg-white"}
function Status({value}:{value:any}){const s=String(value||"").toLowerCase();const tone=s.includes("declin")||s.includes("cancel")?"bg-red-100 text-red-700":s.includes("complete")?"bg-green-100 text-green-700":s.includes("progress")||s.includes("won")?"bg-blue-100 text-blue-700":s.includes("await")?"bg-amber-100 text-amber-800":"bg-[#f2f2ee] text-black/65";return <span className={"inline-flex rounded-full px-2.5 py-1 text-xs font-black capitalize "+tone}>{statusLabel(value)||"Not set"}</span>}
function Stat({label,value}:{label:string,value:string}){return <div className="rounded-2xl border border-black/10 bg-white p-4"><p className="text-xs font-black uppercase tracking-wider text-black/40">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
function Table({rows,cols,render}:{rows:any[],cols:string[],render:(r:any)=>React.ReactNode[]}){return <div className="mt-5 overflow-hidden rounded-2xl border border-black/10 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#f2f2ee] text-xs uppercase tracking-wider text-black/45"><tr>{cols.map(c=><th key={c} className="px-4 py-3">{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||r.reference||i} className={"border-t border-black/8 "+rowTone(r.status||r.job?.status)}>{render(r).map((v,n)=><td key={n} className="px-4 py-4">{v}</td>)}</tr>)}</tbody></table></div>{rows.length===0&&<p className="p-8 text-center text-sm text-black/45">No records found.</p>}</div>}

function HistoricalInvoiceModal({jobs,onClose,onSaved}:{jobs:any[],onClose:()=>void,onSaved:()=>void}){const [jobId,setJobId]=useState(""),[invoiceNumber,setInvoiceNumber]=useState(""),[invoiceDate,setInvoiceDate]=useState(""),[amount,setAmount]=useState(""),[status,setStatus]=useState("PAID"),[saving,setSaving]=useState(false),[error,setError]=useState("");async function save(){setSaving(true);setError("");const r=await fetch("/api/admin/invoices/historical",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId,invoiceNumber,invoiceDate:invoiceDate||null,amount:Number(amount),status})});const b=await r.json().catch(()=>({}));setSaving(false);if(!r.ok){setError(b.error||"Unable to add invoice");return;}onSaved();}return <div className="fixed inset-0 z-50 grid place-items-center bg-black/35 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-xl"><div className="flex items-start justify-between"><div><h2 className="text-xl font-black">Add historical invoice</h2><p className="mt-1 text-sm text-black/50">Record an old invoice without sending anything to the customer.</p></div><button onClick={onClose} className="text-xl">×</button></div><div className="mt-5 grid gap-3"><select value={jobId} onChange={e=>setJobId(e.target.value)} className="h-11 rounded-xl border border-black/15 bg-white px-3"><option value="">Select job</option>{jobs.map(j=><option key={j.id} value={j.id}>{j.reference} · {j.customerName}</option>)}</select><input value={invoiceNumber} onChange={e=>setInvoiceNumber(e.target.value)} placeholder="Invoice number" className="h-11 rounded-xl border border-black/15 px-3"/><input type="date" value={invoiceDate} onChange={e=>{setInvoiceDate(e.target.value);requestAnimationFrame(()=>e.target.blur())}} className="h-11 rounded-xl border border-black/15 px-3"/><input type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Invoice total (£)" className="h-11 rounded-xl border border-black/15 px-3"/><select value={status} onChange={e=>setStatus(e.target.value)} className="h-11 rounded-xl border border-black/15 bg-white px-3"><option value="PAID">Paid</option><option value="AUTHORISED">Unpaid</option><option value="DRAFT">Draft</option></select>{error&&<p className="text-sm font-bold text-red-700">{error}</p>}<div className="flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border border-black/15 px-4 py-2.5 text-sm font-bold">Cancel</button><button disabled={saving||!jobId||!invoiceNumber||!amount} onClick={save} className="rounded-xl bg-[#e66a24] px-4 py-2.5 text-sm font-black text-white disabled:opacity-40">{saving?"Adding...":"Add invoice"}</button></div></div></div></div>}
