"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
type View="customers"|"jobs"|"quotes"|"invoices"|"payments"|"files"|"team";
const titles:any={customers:["Customers","Every customer and their jobs in one place."],jobs:["Jobs","All current work and enquiries."],quotes:["Quotes","Quotes across every job."],invoices:["Invoices","Jobs at invoice and payment stage."],payments:["Payments","Customer payments and outstanding balances."],files:["Files","Open job files and photos from one place."],team:["Team","People assigned across your work."]};
const money=(v:any)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(Number(v||0));
export default function BusinessDirectory({view}:{view:View}){const [jobs,setJobs]=useState<any[]>([]),[people,setPeople]=useState<any[]>([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{fetch("/api/admin/jobs",{cache:"no-store"}).then(async r=>{if(r.status===401){location.href="/admin/login";return;}const b=await r.json();if(!r.ok)setError(b.error||"Unable to load records");else{setJobs((b.jobs||[]).filter((x:any)=>!x.isPlaceholder));setPeople(b.people||[]);}setLoading(false);}).catch(()=>{setError("Unable to load records");setLoading(false);});},[]);
const rows=useMemo(()=>{const s=q.toLowerCase().trim();return jobs.filter(j=>!s||[j.reference,j.customerName,j.address,j.postcode,j.jobType,j.email,j.phone].join(" ").toLowerCase().includes(s));},[jobs,q]);
const customers=useMemo(()=>{const m=new Map<string,any>();rows.forEach(j=>{const k=j.customerId||j.customerName;const x=m.get(k)||{id:k,name:j.customerName,email:j.email,phone:j.phone,address:j.address,postcode:j.postcode,jobs:[]};x.jobs.push(j);m.set(k,x);});return [...m.values()].sort((a,b)=>a.name.localeCompare(b.name));},[rows]);
const payments=rows.flatMap(j=>(j.customerPayments||[]).map((p:any)=>({...p,job:j})));
const [title,desc]=titles[view];\nconst statuses=useMemo(()=>Array.from(new Set(jobs.map(j=>String(j.status||""))).values()).filter(Boolean).sort(),[jobs]);\nconst [statusFilter,setStatusFilter]=useState("all");\nconst visibleRows=useMemo(()=>rows.filter(j=>statusFilter==="all"||j.status===statusFilter),[rows,statusFilter]);
return <main className="min-h-screen bg-[#f5f5f2] px-4 py-7 text-[#141414] sm:px-5 lg:px-8"><div className="mx-auto max-w-[1500px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#e66a24]">Business Management Software</p><h1 className="mt-1 text-3xl font-black">{title}</h1><p className="mt-1 text-sm text-black/50">{desc}</p></div>{view==="jobs"&&<Link href="/admin/jobs/new" className="rounded-xl bg-[#e66a24] px-4 py-2.5 text-sm font-black text-white">+ New job</Link>}</div><div className="mt-5 rounded-2xl border border-black/10 bg-white p-3"><div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_220px]"><input value={q} onChange={e=>setQ(e.target.value)} placeholder={"Search "+title.toLowerCase()+"..."} className="h-11 w-full rounded-xl border border-black/15 px-3 text-sm outline-none"/>{!["customers","team"].includes(view)&&<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="h-11 rounded-xl border border-black/15 bg-white px-3 text-sm font-bold"><option value="all">All statuses</option>{statuses.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select>}</div></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}{loading&&<p className="mt-5 rounded-2xl bg-white p-8 text-center text-black/45">Loading...</p>}
{!loading&&view==="customers"&&<div className="mt-5 grid gap-3">{customers.map(c=><section key={c.id} className="rounded-2xl border border-black/10 bg-white p-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-black">{c.name}</h2><p className="text-xs text-black/50">{[c.address,c.postcode,c.email,c.phone].filter(Boolean).join(" · ")}</p></div><b>{c.jobs.length} job{c.jobs.length===1?"":"s"}</b></div><div className="mt-3 flex flex-wrap gap-2">{c.jobs.map((j:any)=><Link key={j.id} href={"/admin/jobs/"+j.reference} className="rounded-lg bg-[#f5f5f2] px-3 py-2 text-xs font-bold"><span className="text-[#e66a24]">{j.reference}</span> · {j.jobType}</Link>)}</div></section>)}</div>}
{!loading&&view==="jobs"&&<Table rows={visibleRows} cols={["Job","Customer","Work","Status","Value"]} render={j=>[<Link className="font-black text-[#e66a24]" href={"/admin/jobs/"+j.reference}>{j.reference}</Link>,j.customerName,j.jobType,<Status value={j.status}/>,money(j.quotedAmount??j.preliminaryEstimate)]}/>}
{!loading&&view==="quotes"&&<Table rows={visibleRows.filter(j=>j.preliminaryEstimate!=null||j.quotedAmount!=null)} cols={["Job","Customer","Estimate","Final quote","Sent"]} render={j=>[<Link className="font-black text-[#e66a24]" href={"/admin/jobs/"+j.reference}>{j.reference}</Link>,j.customerName,money(j.preliminaryEstimate),j.quotedAmount!=null?money(j.quotedAmount):"Not finalised",j.quoteSentAt?new Date(j.quoteSentAt).toLocaleDateString("en-GB"):"Not sent"]}/>}
{!loading&&view==="invoices"&&<Table rows={visibleRows.filter(j=>j.balanceActive||j.status==="awaiting_final_payment"||j.status==="completed")} cols={["Job","Customer","Job value","Received","Outstanding"]} render={j=>[<Link className="font-black text-[#e66a24]" href={"/admin/jobs/"+j.reference}>{j.reference}</Link>,j.customerName,money(j.quotedAmount),money(j.amountPaid),money(j.balanceOutstanding)]}/>}
{!loading&&view==="payments"&&<><div className="mt-5 grid gap-3 sm:grid-cols-3"><Stat label="Received" value={money(rows.reduce((s,j)=>s+Number(j.amountPaid||0),0))}/><Stat label="Outstanding" value={money(rows.reduce((s,j)=>s+Number(j.balanceOutstanding||0),0))}/><Stat label="Payments recorded" value={String(payments.length)}/></div><Table rows={payments} cols={["Job","Customer","Payment","Date","Amount"]} render={p=>[<Link className="font-black text-[#e66a24]" href={"/admin/jobs/"+p.job.reference}>{p.job.reference}</Link>,p.job.customerName,p.payment_type||"Payment",new Date(p.paid_at||p.created_at).toLocaleDateString("en-GB"),money(p.amount)]}/></>}
{!loading&&view==="files"&&<div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{visibleRows.map(j=><Link key={j.id} href={"/admin/jobs/"+j.reference} className="rounded-2xl border border-black/10 bg-white p-4 hover:bg-[#fffaf6]"><b className="text-[#e66a24]">{j.reference}</b><h2 className="mt-1 font-black">{j.customerName}</h2><p className="mt-1 text-sm text-black/50">{j.jobType}</p><p className="mt-4 text-xs font-bold">Open photos & files →</p></Link>)}</div>}
{!loading&&view==="team"&&<div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{people.map((p:any)=><section key={p.id} className="rounded-2xl border border-black/10 bg-white p-4"><h2 className="font-black">{p.name}</h2><p className="text-sm text-black/50">{p.company||String(p.relationship_type||"Team member").replaceAll("_"," ")}</p></section>)}</div>}</div></main>}
function Status({value}:{value:any}){const s=String(value||"").toLowerCase();const tone=s.includes("declin")||s.includes("cancel")?"bg-red-100 text-red-700":s.includes("complete")?"bg-green-100 text-green-700":s.includes("progress")||s.includes("won")?"bg-blue-100 text-blue-700":s.includes("await")?"bg-amber-100 text-amber-800":"bg-[#f2f2ee] text-black/65";return <span className={"inline-flex rounded-full px-2.5 py-1 text-xs font-black capitalize "+tone}>{s.replaceAll("_"," ")||"Not set"}</span>}\nfunction Stat({label,value}:{label:string,value:string}){return <div className="rounded-2xl border border-black/10 bg-white p-4"><p className="text-xs font-black uppercase tracking-wider text-black/40">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
function Table({rows,cols,render}:{rows:any[],cols:string[],render:(r:any)=>React.ReactNode[]}){return <div className="mt-5 overflow-hidden rounded-2xl border border-black/10 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#f2f2ee] text-xs uppercase tracking-wider text-black/45"><tr>{cols.map(c=><th key={c} className="px-4 py-3">{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||r.reference||i} className="border-t border-black/8 hover:bg-[#fffaf6]">{render(r).map((v,n)=><td key={n} className="px-4 py-4">{v}</td>)}</tr>)}</tbody></table></div>{rows.length===0&&<p className="p-8 text-center text-sm text-black/45">No records found.</p>}</div>}
