"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ALL_STATUSES, JOB_TYPES, STATUS_META } from "@/lib/crm/constants";
import type { JobStatus, Manager } from "@/lib/crm/types";

function money(value?: number) { return new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 0 }).format(Number(value || 0)); }
function when(value?: string) { if (!value) return "Not set"; return new Intl.DateTimeFormat("en-GB", { day:"2-digit", month:"short", hour:"2-digit", minute:"2-digit" }).format(new Date(value)); }
function statusOrder(value: unknown) { return STATUS_META[value as JobStatus]?.order ?? 0; }
function statusLabel(value: unknown) { return STATUS_META[value as JobStatus]?.label ?? String(value || ""); }

export default function CrmDashboardV2() {
  const router=useRouter();
  const [jobs,setJobs]=useState<any[]>([]); const [activities,setActivities]=useState<any[]>([]); const [admin,setAdmin]=useState<any>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [query,setQuery]=useState(""); const [status,setStatus]=useState<JobStatus|"all">("all"); const [manager,setManager]=useState<Manager|"all">("all"); const [type,setType]=useState("all");

  useEffect(()=>{let cancelled=false;async function load(){const [jr,dr]=await Promise.all([fetch("/api/admin/jobs",{cache:"no-store"}),fetch("/api/admin/dashboard",{cache:"no-store"})]);if(jr.status===401||dr.status===401){router.replace("/admin/login");return;}const jb=await jr.json().catch(()=>({}));const db=await dr.json().catch(()=>({}));if(!jr.ok){if(!cancelled){setError(jb.error||"Unable to load CRM");setLoading(false);}return;}if(!cancelled){setJobs(jb.jobs||[]);setActivities(db.activities||[]);setAdmin(jb.admin||db.admin||null);setLoading(false);}}void load();return()=>{cancelled=true;};},[router]);

  const now=Date.now();
  const counts=useMemo(()=>({
    newEnquiries:jobs.filter(j=>j.status==="new_enquiry").length,
    siteVisits:jobs.filter(j=>["site_visit_required","site_visit_booked"].includes(j.status)).length,
    quotes:jobs.filter(j=>["quote_preparing","quote_sent","awaiting_customer"].includes(j.status)).length,
    deposits:jobs.filter(j=>j.status==="deposit_requested").length,
    fabrication:jobs.filter(j=>j.status==="fabrication").length,
    installs:jobs.filter(j=>j.status==="installation_scheduled").length,
    due:jobs.filter(j=>j.nextActionAt&&new Date(j.nextActionAt).getTime()<=now).length,
    outstanding:jobs.reduce((s,j)=>s+Number(j.balanceOutstanding||0),0),
  }),[jobs,now]);

  const myDue=useMemo(()=>jobs.filter(j=>j.nextActionAt&&new Date(j.nextActionAt).getTime()<=now&&(!j.nextActionAssignee||j.nextActionAssignee===admin?.initials)).sort((a,b)=>new Date(a.nextActionAt).getTime()-new Date(b.nextActionAt).getTime()),[jobs,admin,now]);
  const filtered=useMemo(()=>jobs.filter(j=>status==="all"||j.status===status).filter(j=>manager==="all"||j.manager===manager).filter(j=>type==="all"||j.jobType===type).filter(j=>`${j.reference} ${j.customerName} ${j.address} ${j.postcode||""} ${j.phone||""} ${j.email||""}`.toLowerCase().includes(query.toLowerCase().trim())).sort((a,b)=>statusOrder(a.status)-statusOrder(b.status)||new Date(b.updatedAt).getTime()-new Date(a.updatedAt).getTime()),[jobs,status,manager,type,query]);

  async function logout(){await fetch("/api/admin/auth/logout",{method:"POST"});router.replace("/admin/login");router.refresh();}
  const cards=[
    ["New enquiries",counts.newEnquiries,"new_enquiry"],["Site visits",counts.siteVisits,"site_visit_required"],["Quotes in play",counts.quotes,"quote_preparing"],["Deposits due",counts.deposits,"deposit_requested"],["Fabrication",counts.fabrication,"fabrication"],["Installations",counts.installs,"installation_scheduled"],["Actions due",counts.due,"all"],["Outstanding",money(counts.outstanding),"all"],
  ] as const;

  return <main className="min-h-screen bg-[#f5f5f2] text-[#141414]">
    <header className="border-b border-black/10 bg-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-5 py-4 lg:px-8"><div className="flex items-center gap-4"><img src="/images/logo.png" alt="M&J Metal" className="h-14 w-auto object-contain"/><div><h1 className="text-2xl font-black tracking-tight">CRM & Job Management</h1><p className="text-sm text-black/45">Live operational dashboard</p></div></div><div className="flex items-center gap-2">{admin?.display_name&&<span className="hidden rounded-full bg-[#f3f3ef] px-3 py-2 text-sm font-semibold sm:inline">{admin.display_name}</span>}<a href="/admin/archive" className="hidden rounded-xl border border-black/15 px-3 py-2.5 text-sm font-bold md:block">Archive</a><a href="/admin/integrations" className="hidden rounded-xl border border-black/15 px-3 py-2.5 text-sm font-bold md:block">Integrations</a><button onClick={()=>void logout()} className="hidden rounded-xl border border-black/15 px-3 py-2.5 text-sm font-bold md:block">Logout</button><a href="/admin/jobs/new" className="rounded-xl bg-[#e66a24] px-4 py-2.5 text-sm font-black text-white">+ New job</a></div></div></header>
    <div className="mx-auto max-w-[1500px] px-5 py-6 lg:px-8">
      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{cards.map(([label,value,filter])=><button key={label} onClick={()=>setStatus(filter as JobStatus|"all")} className="rounded-2xl border border-black/10 bg-white p-4 text-left shadow-[0_8px_30px_rgba(0,0,0,0.04)]"><p className="text-xs font-bold uppercase tracking-[0.06em] text-black/45">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></button>)}</section>
      <section className="mt-6 grid gap-5 xl:grid-cols-[1fr_420px]"><div>
        <div className="rounded-2xl border border-black/10 bg-white p-4"><div className="grid gap-3 lg:grid-cols-[minmax(240px,1fr)_220px_180px_220px]"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ref, customer, address, postcode, phone..." className="h-11 rounded-xl border border-black/15 px-3 text-sm"/><select value={status} onChange={e=>setStatus(e.target.value as JobStatus|"all")} className="h-11 rounded-xl border border-black/15 px-3 text-sm"><option value="all">All statuses</option>{ALL_STATUSES.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select><select value={manager} onChange={e=>setManager(e.target.value as Manager|"all")} className="h-11 rounded-xl border border-black/15 px-3 text-sm"><option value="all">Mark + Jonathan</option><option value="MD">Mark</option><option value="JB">Jonathan</option></select><select value={type} onChange={e=>setType(e.target.value)} className="h-11 rounded-xl border border-black/15 px-3 text-sm"><option value="all">All job types</option>{JOB_TYPES.map(t=><option key={t}>{t}</option>)}</select></div></div>
        {error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}
        <div className="mt-4 overflow-hidden rounded-2xl border border-black/10 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead className="bg-[#f2f2ee] text-xs uppercase tracking-[0.08em] text-black/50"><tr><th className="px-4 py-3">Ref</th><th className="px-4 py-3">Customer / site</th><th className="px-4 py-3">Job</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Manager</th><th className="px-4 py-3">Value</th><th className="px-4 py-3">Next action</th><th className="px-4 py-3"></th></tr></thead><tbody>{filtered.map(j=><tr key={j.id} className="border-t border-black/8 align-top hover:bg-[#fffaf6]"><td className="px-4 py-4 font-black text-[#e66a24]">{j.reference}</td><td className="px-4 py-4"><b>{j.customerName}</b><p className="mt-1 text-sm text-black/45">{j.address} {j.postcode}</p></td><td className="px-4 py-4"><b>{j.jobType}</b><p className="mt-1 text-xs text-black/45">{(j.finishes||[]).join(" + ")||"Finish TBC"}</p></td><td className="px-4 py-4"><span className="rounded-full bg-[#f3f3ef] px-3 py-1.5 text-xs font-bold">{statusLabel(j.status)}</span></td><td className="px-4 py-4 font-bold">{j.manager==="MD"?"Mark":"Jonathan"}</td><td className="px-4 py-4 font-bold">{money(j.agreedAmount??j.quotedAmount)}</td><td className="px-4 py-4"><b className={j.nextActionAt&&new Date(j.nextActionAt).getTime()<=now?"text-red-700":""}>{j.nextAction||"No next action"}</b><p className="mt-1 text-xs text-black/45">{when(j.nextActionAt)}{j.nextActionAssignee?` • ${j.nextActionAssignee==="MD"?"Mark":"Jonathan"}`:""}</p></td><td className="px-4 py-4"><a href={`/admin/jobs/${j.reference}`} className="rounded-lg border border-black/15 px-3 py-2 text-sm font-bold">Open</a></td></tr>)}</tbody></table></div>{loading&&<p className="p-8 text-center text-black/45">Loading jobs...</p>}{!loading&&filtered.length===0&&<p className="p-8 text-center text-black/45">No jobs match these filters.</p>}</div>
      </div><aside className="space-y-5"><section className="rounded-2xl border border-black/10 bg-white p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-black">Actions due</h2><span className="rounded-full bg-red-50 px-2.5 py-1 text-xs font-black text-red-700">{myDue.length}</span></div><div className="mt-4 space-y-2">{myDue.slice(0,8).map(j=><a key={j.id} href={`/admin/jobs/${j.reference}`} className="block rounded-xl bg-[#f5f5f2] p-3"><div className="flex justify-between gap-3"><b>{j.reference}</b><span className="text-xs text-red-700">{when(j.nextActionAt)}</span></div><p className="mt-1 text-sm font-semibold">{j.nextAction}</p><p className="text-xs text-black/45">{j.customerName}</p></a>)}{myDue.length===0&&<p className="text-sm text-black/45">Nothing overdue for you.</p>}</div></section>
        <section className="rounded-2xl border border-black/10 bg-white p-5"><h2 className="text-lg font-black">Recent activity</h2><div className="mt-4 space-y-3">{activities.map((a:any)=><a key={a.id} href={a.mj_jobs?.reference?`/admin/jobs/${a.mj_jobs.reference}`:"/admin"} className="block border-b border-black/8 pb-3 last:border-0"><div className="flex justify-between gap-3"><b className="text-sm">{a.summary}</b><span className="whitespace-nowrap text-xs text-black/40">{when(a.occurred_at)}</span></div><p className="mt-1 text-xs text-black/45">{a.mj_jobs?.reference||"CRM"}{a.actor?` • ${a.actor==="MD"?"Mark":"Jonathan"}`:""}</p></a>)}{activities.length===0&&<p className="text-sm text-black/45">No activity yet.</p>}</div></section></aside></section>
    </div>
  </main>;
}
